### ISSUE TITLE
Migrating this repo to Lunarmodules

### ISSUE THREAD

**Issue by Tieske** [lunarmodules/lua-mimetypes#1]
I have set up a maintainer team for this repo, and added @teto.

@hishamhm can you move the luarocks entry over to the "lunarmodules"?
@alerque can you add the lunarmodules apikey as a secret so the automated deployment can be set up?

**Comment by hishamhm** [comment]
> @hishamhm can you move the luarocks entry over to the "lunarmodules"?

Done!

**Comment by Tieske** [comment]
@alerque can you also change the homepage on the luarocks site? to point to the new lunarmodules repo location

**Comment by alerque** [comment]
@Tieske The API key is in the org and available to all repositories. I updated the profile page on LuaRocks with the current URL. I also opened a PR with some other changes.

**Comment by Tieske** [comment]
> The API key is in the org and available to all repositories.

wasn't aware, sorry for the noise.
